server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy requests starting with /api to the backend container
    location /api/ {
        proxy_pass http://backend_service:3000/;
        proxy_set_header Host $host;
    }
}